var TodoViewConstants = {
  TODO_VIEW_CREATE: 'TODO_ITEM_VIEW_CREATED',

  TODO_VIEW_DESTROY: 'TODO_ITEM_VIEW_DESTROYED',

  TODO_VIEW_READY: 'TODO_ITEM_VIEW_READYED'
};

module.exports = TodoViewConstants;
