var TodoConstants = {
  TODO_CREATE: 'TODO_ITEM_CREATED',

  TODO_DESTROY: 'TODO_ITEM_DESTROYED',

  TODO_READY: 'TODO_ITEM_READYED',

  TODO_UPLOAD: 'TODO_ITEM_UPLOADED'
};

module.exports = TodoConstants;
